voxelisation.py:
  working_dir: '/mnt/data-01/nmunger/proj-qalidar/data'
  mode:
    multiple_files: False # Whether to run on multiple files contained in a folder
  vox_dimension: 1.5 # Size of the voxel to use in meters
  data:
    single_tile: # If multiple_files=False, will run only on this tile
      prev_tile_name: '2546500_1211000.las' 
    folder:  
      prev_folder: 'initial_input_pcd/2018_NE_retiled'
      new_folder: 'initial_input_pcd/2022_Neuchatel'
  classes_correspondence: 'classes_equivalence.csv' 
  output_dir: 'out_dataframe/voxelised_comparison'
    